server:
   port: 8091
spring:
   redis:
      cluster:
         ## 集群ip端口
          nodes: 54.179.184.125:7001,54.179.184.125:7002,54.169.76.123:7003,54.169.76.123:7004,54.255.85.152:7005,54.255.85.152:7006
       ## 密码
      password: chuanzhangredis
         jedis:
           pool:
             ## 连接池最大连接数（使用负值表示没有限制）
             max-active: 300
             ## 连接池最大阻塞等待时间（使用负值表示没有限制）
             max-wait: -1ms
             ## 连接池中的最大空闲连接
             max-idle: 100
             ## 连接池中的最小空闲连接
             min-idle: 20
       ## Redis数据库索引(默认为0)
      # database: 0
         ## 连接超时时间（毫秒）
      timeout: 60000