#spring.data.mongodb.host=54.169.76.123
#spring.data.mongodb.port=25786
#spring.data.mongodb.database=exchangedev3
#spring.data.mongodb.username=exchangedev123
#spring.data.mongodb.password=exchangedev@56
spring:
  data:
    mongodb:
      uri: mongodb://exchange_dev1:exchange_dev321@54.169.76.123:25786/exchange_dev

# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7777
  connection-timeout: 5000ms
  servlet:
    context-path: /mongo

